package tests;

import org.testng.Assert;
import org.testng.annotations.Test;

import pages.HomePage;
import pages.LoginPage;
import pages.ProfileEditModal;
import utils.ConfigReader;

import java.util.UUID;


public class UserWorkflowTest extends BaseTest {
    
    private HomePage homePage;

    @Test(description = "Step 1: Verify successful login")
    public void loginTest() {
        homePage = new HomePage(driver);
        homePage.navigateToHomePage();

        // Login with valid credentials
        LoginPage loginPage = homePage.header.clickLogin();
        // Navigates back to the homepage (history test)
        driver.navigate().back();
        // Navigates forward to the login page  (history test)

        driver.navigate().forward();

        loginPage.login(ConfigReader.getProperty("username"), ConfigReader.getProperty("password"));
        
        // Verify that we are logged in
        Assert.assertTrue(homePage.header.isUserLoggedIn(), "User should be logged in but is not.");
    }

    // This test depends on the successful login test, so it will only run if loginTest() passes
    @Test(dependsOnMethods = {"loginTest"}, description = "Step 2: Verify updating profile bio form as a logged-in user")
    public void updateProfileTest() {
        ProfileEditModal profileModal = homePage.header.goToProfileEdit();

        //  Generate random test data dynamically using UUID
        String randomBioText = "Autogenerated Bio String ID: " + UUID.randomUUID().toString().substring(0, 8);
        
        // Update the profile bio with new text
        profileModal.updateProfileInformation(randomBioText);

        // Verify that the profile update was successful
        Assert.assertEquals(profileModal.getBioText(),randomBioText,
                "Profile sync failed: Live biography text does not match external properties value.");
    }

    // This test depends on the successful profile update test, so it will only run if updateProfileTest() passes
    @Test(dependsOnMethods = {"updateProfileTest"}, description = "Step 3: Verify successful logout")
    public void logoutTest() {
        // Log out action
        homePage.header.logout();

        // Assertion: Confirm user indicators are wiped completely from the current context
        Assert.assertFalse(homePage.header.isUserLoggedIn(), "Session drop failed: User authentication state flag remained active.");
    }
}